site_name: ActiveDirectoryToolkit Documentation
repo_url: https://github.com/twillin912/ActiveDirectoryToolkit
theme: readthedocs
pages:
  - Home: index.md
  - ActiveDirectoryToolkit Basics:
    - Quick Start: quickstart.md
  - Functions:

